server:
  error:
    include-stack-trace: on_param

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/celtic-bank?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG

