server:
  error:
    include-stack-trace: on_param

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/celtic-bank?useSSL=false&createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update

